export const UserData = [
	{
		name: 'January',
		'User Count': 4000,
	},
	{
		name: 'February',
		'User Count': 3000,
	},
	{
		name: 'March',
		'User Count': 2000,
	},
	{
		name: 'April',
		'User Count': 2780,
	},
	{
		name: 'May',
		'User Count': 1890,
	},
	{
		name: 'June',
		'User Count': 2390,
	},
	{
		name: 'July',
		'User Count': 3490,
	},
	{
		name: 'August',
		'User Count': 1490,
	},
	{
		name: 'September',
		'User Count': 3090,
	},
	{
		name: 'October',
		'User Count': 1000,
	},
	{
		name: 'November',
		'User Count': 2120,
	},
	{
		name: 'December',
		'User Count': 6000,
	},
];

export const userRows = [
	{
		id: 1,
		username: 'Vedansh Dwivedi',
		avatar: 'https://avatars.githubusercontent.com/u/25373561?v=4',
		email: 'vedansh@gmail.com',
		status: 'active',
		transaction: '$120.00',
	},
	{
		id: 2,
		username: 'Vedansh Dwivedi',
		avatar: 'https://avatars.githubusercontent.com/u/25373561?v=4',
		email: 'vedansh@gmail.com',
		status: 'active',
		transaction: '$120.00',
	},
	{
		id: 3,
		username: 'Vedansh Dwivedi',
		avatar: 'https://avatars.githubusercontent.com/u/25373561?v=4',
		email: 'vedansh@gmail.com',
		status: 'active',
		transaction: '$120.00',
	},
	{
		id: 4,
		username: 'Vedansh Dwivedi',
		avatar: 'https://avatars.githubusercontent.com/u/25373561?v=4',
		email: 'vedansh@gmail.com',
		status: 'inactive',
		transaction: '$120.00',
	},
	{
		id: 5,
		username: 'Vedansh Dwivedi',
		avatar: 'https://avatars.githubusercontent.com/u/25373561?v=4',
		email: 'vedansh@gmail.com',
		status: 'active',
		transaction: '$120.00',
	},
	{
		id: 6,
		username: 'Vedansh Dwivedi',
		avatar: 'https://avatars.githubusercontent.com/u/25373561?v=4',
		email: 'vedansh@gmail.com',
		status: 'active',
		transaction: '$120.00',
	},
	{
		id: 7,
		username: 'Vedansh Dwivedi',
		avatar: 'https://avatars.githubusercontent.com/u/25373561?v=4',
		email: 'vedansh@gmail.com',
		status: 'active',
		transaction: '$120.00',
	},
	{
		id: 8,
		username: 'Vedansh Dwivedi',
		avatar: 'https://avatars.githubusercontent.com/u/25373561?v=4',
		email: 'vedansh@gmail.com',
		status: 'active',
		transaction: '$120.00',
	},
	{
		id: 9,
		username: 'Vedansh Dwivedi',
		avatar: 'https://avatars.githubusercontent.com/u/25373561?v=4',
		email: 'vedansh@gmail.com',
		status: 'inactive',
		transaction: '$120.00',
	},
	{
		id: 10,
		username: 'Vedansh Dwivedi',
		avatar: 'https://avatars.githubusercontent.com/u/25373561?v=4',
		email: 'vedansh@gmail.com',
		status: 'active',
		transaction: '$120.00',
	},
	{
		id: 11,
		username: 'Vedansh Dwivedi',
		avatar: 'https://avatars.githubusercontent.com/u/25373561?v=4',
		email: 'vedansh@gmail.com',
		status: 'active',
		transaction: '$120.00',
	},
	{
		id: 12,
		username: 'Vedansh Dwivedi',
		avatar: 'https://avatars.githubusercontent.com/u/25373561?v=4',
		email: 'vedansh@gmail.com',
		status: 'active',
		transaction: '$120.00',
	},
	{
		id: 13,
		username: 'Vedansh Dwivedi',
		avatar: 'https://avatars.githubusercontent.com/u/25373561?v=4',
		email: 'vedansh@gmail.com',
		status: 'active',
		transaction: '$120.00',
	},
	{
		id: 14,
		username: 'Vedansh Dwivedi',
		avatar: 'https://avatars.githubusercontent.com/u/25373561?v=4',
		email: 'vedansh@gmail.com',
		status: 'inactive',
		transaction: '$120.00',
	},
	{
		id: 15,
		username: 'Vedansh Dwivedi',
		avatar: 'https://avatars.githubusercontent.com/u/25373561?v=4',
		email: 'vedansh@gmail.com',
		status: 'active',
		transaction: '$120.00',
	},
];